stages:
  - build_app
  - build_oauth2_proxy
  - build_reverse_proxy

before_script:
  - export HTTP_PROXY=${HTTP_PROXY}
  - export HTTPS_PROXY=${HTTP_PROXY}
  - export NO_PROXY="${NO_PROXY}"
  - echo "{\"auths\":{\"${NEXUS_URL}:5000\":{\"auth\":\"$(echo -n $NEXUS_USER:$NEXUS_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
  - > 
    if [[ ${CI_COMMIT_REF_NAME} = "preprod" ]]; then
      export $(grep -v "^#" ./env/.env.preprod | xargs)
      export APP_CERTIFICATE_PASSWORD=${PREPROD__APP_CERTIFICATE_PASSWORD}
    else
      export $(grep -v "^#" ./env/.env.dev | xargs)
      export APP_CERTIFICATE_PASSWORD=${DEV__APP_CERTIFICATE_PASSWORD}
    fi

job:build:app:dev:
  stage: build_app
  image:
    name: ${NEXUS_URL}:5001/kaniko-executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --insecure-registry "${NEXUS_URL}:5000"
      --skip-tls-verify
      --context "dir://app"
      --dockerfile "Dockerfile"
      --build-arg HTTP_PROXY=${HTTP_PROXY}
      --build-arg VITE_API_BASE_URL=${VITE_API_BASE_URL}
      --build-arg VITE_LOGOUT_URL=${VITE_LOGOUT_URL}
      --build-arg VITE_MATOMO_SITE_ID=${VITE_MATOMO_SITE_ID}
      --build-arg VITE_MATOMO_URL=${VITE_MATOMO_URL}
      --build-arg VITE_APP_URL=${APP_URL}
      --destination "${NEXUS_URL}:5000/${NEXUS_REPOSITORY}/front/app:${APP_IMAGE_TAG}"
  only:
    - dev@champollion/front-it
    - preprod@champollion/front-it
  tags:
    - CHAM

job:build:oauth2-proxy:dev:
  stage: build_oauth2_proxy
  image:
    name: ${NEXUS_URL}:5001/kaniko-executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --insecure-registry "${NEXUS_URL}:5000"
      --skip-tls-verify
      --context "dir://oauth2-proxy"
      --dockerfile "Dockerfile"
      --destination "${NEXUS_URL}:5000/${NEXUS_REPOSITORY}/front/oauth2-proxy:${OAUTH2_PROXY_IMAGE_TAG}"
  only:
    - dev@champollion/front-it
    - preprod@champollion/front-it
  tags:
    - CHAM

job:build:reverse-proxy:dev:
  stage: build_reverse_proxy
  image:
    name: ${NEXUS_URL}:5001/kaniko-executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --insecure-registry "${NEXUS_URL}:5000"
      --skip-tls-verify
      --context "dir://reverse-proxy"
      --dockerfile "Dockerfile"
      --build-arg HTTP_PROXY=${HTTP_PROXY}
      --build-arg APP_CERTIFICATE_FILE=${APP_CERTIFICATE_FILE}
      --build-arg APP_CERTIFICATE_PASSWORD=${APP_CERTIFICATE_PASSWORD}
      --destination "${NEXUS_URL}:5000/${NEXUS_REPOSITORY}/front/reverse-proxy:${REVERSE_PROXY_IMAGE_TAG}"
  only:
    - dev@champollion/front-it
    - preprod@champollion/front-it
  tags:
    - CHAM