version: "3.8"

networks:
  champollion:

services:
  app:
    image: ${NEXUS_CHAMPOLLION_URL}/front/app:${APP_IMAGE_TAG}
    container_name: champollion-${COMPOSE_PROJECT_NAME}-front-app
    environment:
      API_URL: ${API_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
    restart: on-failure
    networks:
      - champollion
    volumes:
    - ${LOGS_STORAGE_PATH}/champollion-front-app-${COMPOSE_PROJECT_NAME}/app:/var/log/nginx
  
  oauth2-proxy:
    image: ${NEXUS_CHAMPOLLION_URL}/front/oauth2-proxy:${OAUTH2_PROXY_IMAGE_TAG}
    container_name: champollion-${COMPOSE_PROJECT_NAME}-front-oauth2-proxy
    restart: on-failure
    networks:
      - champollion
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_REDIRECT_URL: /oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OIDC_ISSUER_URL}/${KEYCLOAK_REALM}
      OAUTH2_PROXY_COOKIE_SECRET: 580b11331e148cacf8428190758c4fe2
      OAUTH2_PROXY_COOKIE_SECURE: 'true' # for local env only
      OAUTH2_PROXY_REVERSE_PROXY: 'true'
      OAUTH2_PROXY_COOKIE_REFRESH: '100ms'
      OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: 'true' # for local env only
      OAUTH2_PROXY_EMAIL_DOMAINS: "*" # allow any email
      OAUTH2_PROXY_UPSTREAMS: 'http://app:8081/'
      OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: 'true' # only for self-signed cert - unknown autority
      OAUTH2_PROXY_HTTP_ADDRESS: 'oauth2-proxy:4180'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_WHITELIST_DOMAIN: ${APP_URL},${AUTH_URL}
    # ports:
    #   - '4180' # commented just for information on port used internally
    healthcheck:
      test: curl --fail http://127.0.0.1/auth/realms/${KEYCLOAK_REALM} || exit 1
      interval: 5s
      retries: 50
      start_period: 0s
      timeout: 3s

  reverse-proxy:
    image: ${NEXUS_CHAMPOLLION_URL}/front/reverse-proxy:${REVERSE_PROXY_IMAGE_TAG}
    container_name: champollion-front-${COMPOSE_PROJECT_NAME}-reverse-proxy
    restart: on-failure
    networks:
      - champollion
    environment:
      APP_URL: ${APP_URL}
      AUTH_URL: ${AUTH_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
    ports:
      - ${REVERSE_PROXY_HTTP_PORT}:80
      - ${REVERSE_PROXY_HTTPS_PORT}:443
    volumes:
      - ${REVERSE_PROXY_SSL_STORAGE_PATH}:/etc/ssl
      - ${LOGS_STORAGE_PATH}/champollion-front-reverse-proxy-${COMPOSE_PROJECT_NAME}/reverse-proxy:/var/log/nginx