version: "3.8"

networks:
  champollion:

services:
  app:
    image: ${DOCKER_NEXUS_REGISTRY}/${DOCKER_NEXUS_REGISTRY_CHAMPOLLION_DIRECTORY}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_DEFAULT_PORT}:80
    restart: on-failure
    networks:
      - champollion