version: "3.8"

networks:
  champollion:

services:
  app:
    image: ${DOCKER_NEXUS_REGISTRY}/${DOCKER_NEXUS_REGISTRY_CHAMPOLLION_DIRECTORY}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
    container_name: ${APP_CONTAINER_NAME}-${ENV}
    ports:
      - ${APP_DEFAULT_PORT}:${APP_DEFAULT_PORT}
    restart: on-failure
    networks:
      - champollion
    volumes:
      - ${APP_SNIPPETS_STORAGE_PATH}:/etc/nginx/snippets
      - ${APP_SSL_STORAGE_PATH}:/etc/ssl
      - ${APP_NGINX_FILE_PATH}:/etc/nginx/conf.d/default.conf