version: "3.8"

networks:
  champollion:
    ipam:
      driver: default
      config:
        - subnet: 192.168.145.0/24

services:
  app:
    image: ${NEXUS_URL}:5000/${NEXUS_REPOSITORY}/front/app:${APP_IMAGE_TAG}
    container_name: champollion-${COMPOSE_PROJECT_NAME}-front-app
    environment:
      API_URL: ${API_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
    restart: on-failure
    networks:
      - champollion
    volumes:
      - ${LOGS_STORAGE_PATH}/champollion-${COMPOSE_PROJECT_NAME}-front-app:/var/log/nginx
  
  oauth2-proxy:
    image: ${NEXUS_URL}:5000/${NEXUS_REPOSITORY}/front/oauth2-proxy:${OAUTH2_PROXY_IMAGE_TAG}
    container_name: champollion-${COMPOSE_PROJECT_NAME}-front-oauth2-proxy
    restart: on-failure
    networks:
      - champollion
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      OAUTH2_PROXY_REDIRECT_URL: /oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://${APP_URL}/auth/realms/${KEYCLOAK_REALM}
      OAUTH2_PROXY_COOKIE_SECRET: 580b11331e148cacf8428190758c4fe2
      OAUTH2_PROXY_COOKIE_SECURE: "true" # for local env only
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_COOKIE_REFRESH: "100ms"
      OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: "false" # for local env only
      OAUTH2_PROXY_EMAIL_DOMAINS: "*" # allow any email
      OAUTH2_PROXY_UPSTREAMS: "http://app:8081/"
      OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true" # only for self-signed cert - unknown autority
      OAUTH2_PROXY_HTTP_ADDRESS: "oauth2-proxy:4180"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_WHITELIST_DOMAIN: ${APP_URL},${AUTH_URL}

  reverse-proxy:
    image: ${NEXUS_URL}:5000/${NEXUS_REPOSITORY}/front/reverse-proxy:${REVERSE_PROXY_IMAGE_TAG}
    container_name: champollion-${COMPOSE_PROJECT_NAME}-front-reverse-proxy
    restart: on-failure
    networks:
      - champollion
    environment:
      APP_URL: ${APP_URL}
      AUTH_URL: ${AUTH_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      IPVM_PRODUCTION_ENS224_PLACEHOLDER: ${IPVM_PRODUCTION_ENS224_PLACEHOLDER}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${LOGS_STORAGE_PATH}/champollion-${COMPOSE_PROJECT_NAME}-front-reverse-proxy:/var/log/nginx