version: "3.8"

networks:
  champollion:

services:
  app:
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
    container_name: ${APP_CONTAINER_NAME}-${ENV}
    restart: on-failure
    networks:
      - champollion
  
  oauth2_proxy:
    image: ${OAUTH2_IMAGE_NAME}:${OAUTH2_IMAGE_TAG}
    container_name: ${OAUTH2_CONTAINER_NAME}-${ENV}
    restart: on-failure
    networks:
      - champollion
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_CLIENT_ID: oauth2-proxy
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_REDIRECT_URL: ${OAUTH2_REDIRECT_URL}
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OIDC_ISSUER_URL}
      OAUTH2_PROXY_COOKIE_SECRET: 580b11331e148cacf8428190758c4fe2
      OAUTH2_PROXY_COOKIE_SECURE: 'true' # for local env only
      OAUTH2_PROXY_REVERSE_PROXY: 'true'
      OAUTH2_PROXY_COOKIE_REFRESH: '100ms'
      OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: 'true' # for local env only
      OAUTH2_PROXY_EMAIL_DOMAINS: "*" # allow any email
      OAUTH2_PROXY_UPSTREAMS: ${OAUTH2_UPSTREAM}
      OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: 'true' # only for self-signed cert - unknown autority
      OAUTH2_PROXY_HTTP_ADDRESS: ${OAUTH2_PROXY_ADDRESS}
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_WHITELIST_DOMAIN: ${OAUTH2_PROXY_WHITELIST}
    # ports:
    #   - '4180' # commented just for information on port used internally
    healthcheck:
      test: curl --fail http://127.0.0.1/auth/realms/app-realm || exit 1
      interval: 5s
      retries: 50
      start_period: 0s
      timeout: 3s

  reverse-proxy:
    image: ${REVERSE_PROXY_IMAGE_NAME}:${REVERSE_PROXY_IMAGE_TAG}
    container_name: ${REVERSE_PROXY_CONTAINER_NAME}-${ENV}
    restart: on-failure
    networks:
      - champollion
    ports:
      - ${REVERSE_PROXY_HTTP_DEFAULT_PORT}:80
      - ${REVERSE_PROXY_HTTPS_DEFAULT_PORT}:443
    volumes:
      - ${REVERSE_PROXY_SSL_STORAGE_PATH}:/etc/ssl