version: "3.8"

networks:
  champollion:

services:
  app:
    image: ${APP_IMAGE_TAG}:${REVERSE_PROXY_IMAGE_TAG}
    container_name: ${APP_CONTAINER_NAME}-${ENV}
    restart: on-failure
    networks:
      - champollion
    #volumes:
    #  - ${APP_NGINX_FILE_PATH}:/etc/nginx/conf.d/default.conf

  reverse-proxy:
    image: ${REVERSE_PROXY_IMAGE_NAME}:${REVERSE_PROXY_IMAGE_TAG}
    container_name: ${REVERSE_PROXY_CONTAINER_NAME}-${ENV}
    restart: on-failure
    networks:
      - champollion
    ports:
      - ${REVERSE_PROXY_HTTP_DEFAULT_PORT}:80
      - ${REVERSE_PROXY_HTTPS_DEFAULT_PORT}:443
    volumes:
      #- ${REVERSE_PROXY_SNIPPETS_STORAGE_PATH}:/etc/nginx/snippets
      - ${REVERSE_PROXY_SSL_STORAGE_PATH}:/etc/ssl
      #- ${REVERSE_PROXY_CONF_STORAGE_PATH}:/etc/nginx/conf.d